[package]
name = "ingest"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
cam = { version = "0.1.0", path = "../cam" }
pcb-core = { workspace = true }

[dev-dependencies]
testkit = { path = "../testkit" }
image = { version = "0.25", default-features = false, features = ["png"] }
